--Q1) --Checking unique values.

SELECT DISTINCT STATUS FROM SALESDATASAMPLE
SELECT DISTINCT YEAR_ID FROM SALESDATASAMPLE
SELECT DISTINCT PRODUCTLINE FROM SALESDATASAMPLE
SELECT DISTINCT COUNTRY FROM SALESDATASAMPLE
SELECT DISTINCT DEALSIZE FROM SALESDATASAMPLE
SELECT DISTINCT TERRITORY FROM SALESDATASAMPLE