--Q2 )Start by grouping sales by productline.

SELECT PRODUCTLINE,SUM(SALES) AS TOTALSALES FROM SALESDATASAMPLE
GROUP BY PRODUCTLINE
ORDER BY 2 DESC --(BY SALES)

SELECT YEAR_ID ,SUM(SALES) FROM SALESDATASAMPLE
GROUP BY YEAR_ID
ORDER BY 1 --(BY YEAR)

SELECT DEALSIZE,SUM(SALES) FROM SALESDATASAMPLE
GROUP BY DEALSIZE
ORDER BY SUM(SALES) -- OR ORDER BY 2