--Q4) What product do they sell in November ?( YEAR=2003 )

SELECT MONTH_ID,PRODUCTLINE ,SUM(SALES)
FROM SALESDATASAMPLE
WHERE MONTH_ID='11' AND YEAR_ID='2004'
GROUP BY MONTH_ID,PRODUCTLINE
ORDER BY 3 DESC
