--STEP(1) 
SELECT *FROM SALESDATASAMPLE

--Q1) --Checking unique values.

SELECT DISTINCT STATUS FROM SALESDATASAMPLE
SELECT DISTINCT YEAR_ID FROM SALESDATASAMPLE
SELECT DISTINCT PRODUCTLINE FROM SALESDATASAMPLE
SELECT DISTINCT COUNTRY FROM SALESDATASAMPLE
SELECT DISTINCT DEALSIZE FROM SALESDATASAMPLE
SELECT DISTINCT TERRITORY FROM SALESDATASAMPLE
--Q2 )Start by grouping sales by productline.

SELECT PRODUCTLINE,SUM(SALES) AS TOTALSALES FROM SALESDATASAMPLE
GROUP BY PRODUCTLINE
ORDER BY 2 DESC --(BY SALES)

SELECT YEAR_ID ,SUM(SALES) FROM SALESDATASAMPLE
GROUP BY YEAR_ID
ORDER BY 1 --(BY YEAR)

SELECT DEALSIZE,SUM(SALES) FROM SALESDATASAMPLE
GROUP BY DEALSIZE
ORDER BY SUM(SALES) -- OR ORDER BY 2

--Q3) What was the best month for sales in a specific year?
--How much was earned that month?

SELECT MONTH_ID,SUM(SALES) AS SALESBYMONTH FROM SALESDATASAMPLE

WHERE YEAR_ID = '2003'
GROUP BY MONTH_ID
ORDER BY 2 DESC -- NOVEMBER=77741826 $

SELECT MONTH_ID,SUM(SALES) AS SALESBYMONTH FROM SALESDATASAMPLE

WHERE YEAR_ID = '2005'
GROUP BY MONTH_ID
ORDER BY 2 DESC --MAY= 31111615 $

--Q4) What product do they sell in November ?( YEAR=2003 )

SELECT MONTH_ID,PRODUCTLINE ,SUM(SALES)
FROM SALESDATASAMPLE
WHERE MONTH_ID='11' AND YEAR_ID='2004'
GROUP BY MONTH_ID,PRODUCTLINE
ORDER BY 3 DESC

--Q5) What city has the highest number of sales in a specific country?

SELECT COUNTRY,SUM(SALES)  FROM SALESDATASAMPLE
GROUP BY COUNTRY
ORDER BY 1 DESC

--Q6) What is the best product in United States ?

SELECT COUNTRY,PRODUCTLINE,YEAR_ID,SUM(SALES) FROM SALESDATASAMPLE WHERE 
COUNTRY='USA'
GROUP BY PRODUCTLINE,COUNTRY,YEAR_ID
ORDER BY 4

--Q7) What is your best customer ? (with RFM METHOD)
DROP TABLE  IF EXISTS #RFM
;WITH RFM AS  
(
SELECT CUSTOMERNAME ,SUM(SALES) AS MONETERYTOTAL,
AVG(SALES) AS AVGMONETERYVALUE,COUNT(ORDERNUMBER) AS FREQUENCY,
MIN (ORDERDATE) LASTORDERDATE,
(SELECT MAX(ORDERDATE) FROM SALESDATASAMPLE ) AS MAXORDERDATE,
DATEDIFF(DAY,MIN (ORDERDATE),(SELECT MAX(ORDERDATE) FROM SALESDATASAMPLE )) AS RECENCY
FROM SALESDATASAMPLE
GROUP BY CUSTOMERNAME
),
RFM_CALC AS 
(
	SELECT R.*,
	NTILE(5) OVER (ORDER BY RECENCY)  AS RECENCY_SCALE,
	NTILE(5) OVER (ORDER BY FREQUENCY) AS FREQUENCY_SCALE ,
	NTILE(5) OVER (ORDER BY MONETERYTOTAL) AS MONETERY_SCALE
	FROM RFM R
)
SELECT RECENCY_SCALE, FREQUENCY_SCALE,MONETERY_SCALE,
(CAST(RECENCY_SCALE AS varchar)+CAST( FREQUENCY_SCALE AS varchar) +CAST(MONETERY_SCALE AS varchar)) AS STRINGSARGUE
INTO #RFM
FROM RFM_CALC C


SELECT RECENCY_SCALE,FREQUENCY_SCALE,MONETERY_SCALE,

	CASE 
		WHEN STRINGSARGUE IN (111,211,221,122,112,144,134,124) THEN 'LOST CUSTOMERS'
		WHEN STRINGSARGUE IN (233,234,235,244,255,312,322,333,511) THEN 'CANNOT LOSE'
		WHEN STRINGSARGUE IN (311,344,355,411,422,421,433) THEN 'POTENTIAL CUSTOMERS'
		WHEN STRINGSARGUE IN (444,522,533,544,555) THEN 'PERFECT CUSTOMERS'

	END AS RFM_SEGMENT
FROM #RFM