--Q3) Write the query that shows how many vehicles there are in each city.
SELECT  C.CITY,COUNT(W.ID) FROM  WEBOFFERS W
INNER JOIN USER_ U ON U.ID=W.USERID
INNER JOIN CITY C ON C.ID=W.CITYID
--INNER JOIN TOWN T ON T.ID=W.TOWNID -- Optional
--INNER JOIN DISTRICT D ON D.ID=W.DISTRICTID --Optional
GROUP BY  C.CITY
ORDER BY 2 DESC --(SOLUTION(1) BY JOIN)

SELECT C.CITY,
(SELECT COUNT(*) FROM WEBOFFERS WHERE CITYID=C.ID) AS COUNTBYCITY
FROM CITY C
ORDER BY 2 DESC --(SOLUTION(2)BY SUBQUERY)