--Q12) Bring the query showing how many men and how many women live in the cities.(SUBQUERY)
SELECT CT.CITY AS SEHIRADI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID) AS MUSTERISAYISI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID AND GENDER='E') AS ERKEKSAYISI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID AND GENDER='K') AS KADINSAYISI
FROM CITIES CT