--Q14)Update the Agegroup field you added to the Customers table as 20-35 years old, 
--36-45 years old, 46-55 years old, 55-65 years old and over 65 years old.

UPDATE CUSTOMERS SET AGEGROUP='BETWEEN 20-35'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35
UPDATE CUSTOMERS SET AGEGROUP='BETWEEN 36-45'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45
UPDATE CUSTOMERS SET AGEGROUP='BETWEEN 46-55'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55
UPDATE CUSTOMERS SET AGEGROUP='BETWEEN 56-65'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65
UPDATE CUSTOMERS SET AGEGROUP='OVER 65'
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65
SELECT *FROM CUSTOMERS -- AS YOU CAN SEE THIS QUERY.