--Q15)Calculate according to the age of the customer in the Customers table,
--and show how many people are in the age ranges. Note: The AGEGROUP columns will not be used.
SELECT 
CASE
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN 'BETWEEN 20-35'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN 'BETWEEN 36-45'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN 'BETWEEN 46-55'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN 'BETWEEN 56-65'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65 THEN 'OVER 65'
END AGEGROUP2,COUNT(*)
FROM CUSTOMERS
GROUP BY 
CASE
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN 'BETWEEN 20-35'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN 'BETWEEN 36-45'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN 'BETWEEN 46-55'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN 'BETWEEN 56-65'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65 THEN 'OVER 65'
END
--OR WE CAN USE THIS WAY.
SELECT AGEGROUP2,COUNT(*) AS CUSTOMERCOUNT  FROM
(
SELECT 
CASE
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN 'BETWEEN 20-35'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN 'BETWEEN 36-45'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN 'BETWEEN 46-55'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN 'BETWEEN 56-65'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65 THEN 'OVER 65'
END AGEGROUP2
FROM CUSTOMERS
) GS
GROUP BY AGEGROUP2 --THIS IS  A DYNAMIC QUERY. WE CONSIDER QUERY LIKE A TABLE.