--Q16) Bring those who live in Istanbul but do not live in Kadýköy by writing a query.

SELECT *FROM CUSTOMERS C 
INNER JOIN CITIES CT ON CT.ID=C.CITYID
INNER JOIN DISTRICTS D ON D.ID=C.DISTRICTID
WHERE CT.CITY='ÝSTANBUL' AND NOT D.DISTRICT='KADIKÖY' --SOLUTION(1)

SELECT *FROM CUSTOMERS C
WHERE CITYID=(SELECT ID FROM CITIES WHERE CITY='ÝSTANBUL') AND
DISTRICTID NOT IN (SELECT ID FROM DISTRICTS WHERE DISTRICT='KADIKÖY')--SOLUTION(2)
