--Q21) Bring the number of people in each distinct. According to the number of cities.

SELECT CT.CITY,D.DISTRICT ,COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
INNER JOIN DISTRICTS D ON D.ID=C.DISTRICTID
GROUP BY CT.CITY,D.DISTRICT
ORDER BY CT.CITY,COUNT(C.ID) DESC
