--Q11) Bring the number of records of customers in the system 
SELECT U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID ) AS ADDRESSCOUNT,( SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN
(SELECT TOP 1 ADDRESSID FROM ORDERS  WHERE USERID=U.ID ORDER BY DATE_ DESC) )


FROM USERS U