--Q3) We want to find out on which day of the week each province does business the most and make a campaign accordingly. 
--Please provide the information on how much sales the cities worship according to the days of the week.

SELECT CITY,DAYOFWEEK_,SUM(LINETOTAL) FROM SALEORDERS
GROUP BY CITY,DAYOFWEEK_
ORDER BY CITY,DAYOFWEEK_
--I try to translate the data into English as much as I can. 
--This is how we can turn the days. The numbers at the beginning allow us to sort the days in order.(Not Alphabetical)

UPDATE SALEORDERS SET DAYOFWEEK_ ='01.MONDAY' WHERE DAYOFWEEK_= '01.PZT' --IN TURKISH PAZARTESÝ = PZT= MONDAY
UPDATE SALEORDERS SET DAYOFWEEK_ ='02.TUESDAY' WHERE DAYOFWEEK_= '02.SAL'-- IN TURKISH SALI = SAL = TUESDAY
UPDATE SALEORDERS SET DAYOFWEEK_ ='03.WEDNESDAY' WHERE DAYOFWEEK_= '03.ÇAR'-- IN TURKISH ÇARÞAMBA = ÇAR = WEDNESDAY
UPDATE SALEORDERS SET DAYOFWEEK_ ='04.THURSDAY' WHERE DAYOFWEEK_= '04.PER'-- IN TURKISH PERÞEMBE = PER = TUESDAY
UPDATE SALEORDERS SET DAYOFWEEK_ ='05.FRIDAY' WHERE DAYOFWEEK_= '05.CUM'-- IN TURKISH CUMA = CUM = FRÝDAY
UPDATE SALEORDERS SET DAYOFWEEK_ ='06.SATURDAY' WHERE DAYOFWEEK_= '06.CMT'-- IN TURKISH CUMARTESÝ = CMT = SATURDAY
UPDATE SALEORDERS SET DAYOFWEEK_ ='07.SUNDAY' WHERE DAYOFWEEK_= '07.PAZ'-- IN TURKISH PAZAR = PAZ = SUNDAY

-- SOLUTION (SUBQUERY )
SELECT  CITY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='01.MONDAY') AS MONDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='02.TUESDAY') AS TUESDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='03.WEDNESDAY') AS WEDNESDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='04.THURSDAY') AS THURSDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='05.FRIDAY') AS FRIDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='06.SATURDAY') AS SATURDAY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND  DAYOFWEEK_='07.SUNDAY') AS SUNDAY
FROM SALEORDERS S
GROUP BY CITY
ORDER BY 1
