--Q4) Find the top 5 best selling categories of each province.

SELECT  S.CITY,S1.CATEGORY1,SUM(S1.TOTALSALE) AS TOTALSALE FROM SALEORDERS S
CROSS APPLY (SELECT TOP 5 CATEGORY1,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY GROUP BY  CATEGORY1 ORDER BY SUM(LINETOTAL)) S1


GROUP BY  CITY,S1.CATEGORY1
ORDER BY  CITY,S1.CATEGORY1

-- WE APPLY CARTESIAN MULTIPLICATION WITH CROSS APPLY.
