--Q5) Find the 3 best-selling categories of each province and the 3 best-selling categories under it.

SELECT S.CITY ,S1.CATEGORY1 ,S2.CATEGORY2,SUM(S1.TOTALSALE ) FROM SALEORDERS S
CROSS APPLY 
(SELECT TOP 3 CATEGORY1,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY GROUP BY CATEGORY1 ORDER BY  SUM(LINETOTAL) DESC ) S1
CROSS APPLY
(SELECT TOP 3 CATEGORY2,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY AND CATEGORY1=S1.CATEGORY1 GROUP BY CATEGORY2 ORDER BY  CATEGORY2,SUM(LINETOTAL) DESC ) S2
GROUP BY S.CITY ,S1.CATEGORY1,S2.CATEGORY2
ORDER BY 1,3,4
