--Q6) Try to get the SALEORDERS table by using join.

SELECT  U.USERNAME_,U.NAMESURNAME,U.TELNR1,U.TELNR2 ,
CT.COUNTRY,CTS.CITY,T.TOWN,ADR.ADDRESSTEXT,O.ID,IT.ITEMNAME,
IT.BRAND,IT.ITEMCODE,IT.CATEGORY1,IT.CATEGORY2,IT.CATEGORY3,IT.CATEGORY4,
OD.AMOUNT,OD.LINETOTAL,O.DATE_,CONVERT(DATE,O.DATE_) AS ORDERDATE,CONVERT(time,O.DATE_),
YEAR(O.DATE_)AS YEAR_,DATENAME(MONTH,O.DATE_) AS MONTH,DATENAME(DW,O.DATE_) AS DAYOFWEEK_
FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
INNER JOIN USERS U ON O.USERID=U.ID --DEPAND EACH OTHER.
INNER JOIN ADDRESS ADR ON ADR.ID=O.ADDRESSID
INNER JOIN COUNTRIES CT ON CT.ID=ADR.COUNTRYID
INNER JOIN CITIES CTS ON CTS.ID=ADR.CITYID
INNER JOIN TOWNS T ON T.ID=ADR.TOWNID
