
--Q7) Using relational tables, 
--write the query that returns how much sales were made in which city.

SELECT CT.CITY,SUM(O.TOTALPRICE) FROM ORDERS O

INNER JOIN ADDRESS AD ON AD.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=AD.CITYID
GROUP BY CT.CITY
ORDER BY 2 DESC --SOLUTION(1)


SELECT C.CITY,
(SELECT SUM(TOTALPRICE) FROM ORDERS WHERE ADDRESSID IN
( SELECT ID FROM ADDRESS WHERE CITYID=C.ID) )
FROM CITIES C --SOLUTION(2)