--Q8)Bring the best-selling 'CATEGORY1' field of each brand according to the main category.

SELECT IT.BRAND, IT.CATEGORY1,SUM(OD.AMOUNT) FROM  ORDERDETAILS OD
INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
GROUP BY IT.BRAND, IT.CATEGORY1
ORDER BY 3 DESC