--Q9) Bring the best-selling brand of each brand according to the main category.

SELECT IT.CATEGORY1,IT.CATEGORY2,IT.BRAND,SUM(OD.AMOUNT) FROM ORDERDETAILS OD

INNER JOIN ITEMS IT ON IT.ID=OD.ORDERID

GROUP BY  IT.CATEGORY1,IT.CATEGORY2,IT.BRAND
ORDER BY SUM(OD.AMOUNT) DESC