--Q1) Please bring the numbers of Women and Men who are still working on a departmental basis in our company.

SELECT DM.DEPARTMENT,P.GENDER,COUNT(P.ID) FROM PERSON P
INNER JOIN POSITION POS ON POS.ID=P.POSITIONID
INNER JOIN DEPARTMENT DM ON DM.ID=P.DEPARTMENTID
WHERE P.OUTDATE IS NULL --> Still working
GROUP BY  DM.DEPARTMENT, P.GENDER
ORDER BY DM.DEPARTMENT, COUNT(P.ID)