--Q11) Please list the departments with an average salary of more than 5500 TL and bring them.

SELECT D.DEPARTMENT,AVG(P.SALARY) AS AVGSALARY FROM PERSON P
INNER JOIN DEPARTMENT D ON D.ID=P.DEPARTMENTID
GROUP BY D.DEPARTMENT
HAVING AVG(P.SALARY)>5500
ORDER BY 1 DESC --SOLUTION(1) (USING JOIN)

SELECT *,
(SELECT ROUND(AVG(SALARY),0) FROM PERSON WHERE DEPARTMENTID=D.ID) AS AVGSALARY
FROM DEPARTMENT D 
WHERE (SELECT AVG(SALARY) FROM PERSON WHERE DEPARTMENTID=D.ID)>5500 --SOLUTION(2) (USING SUBQUERY)
ORDER BY 1
SELECT *FROM
(
SELECT DEPARTMENT,AVG(P.SALARY) AS AVGSALARY 
FROM DEPARTMENT D
INNER JOIN PERSON P ON P.DEPARTMENTID=DEPARTMENTID
GROUP BY DEPARTMENT
) GS WHERE AVGSALARY>5500--SOLUTION(3) (DYNAMIC VÝEW)
