--Q12) Write the query that returns the average working time of the departments.
SELECT DEPARTMENT,AVG(WORKINGTIME) FROM
(
SELECT  D.DEPARTMENT,
CASE 
    WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
	ELSE DATEDIFF(MONTH,INDATE,GETDATE())
END AS WORKINGTIME
FROM PERSON P
INNER JOIN DEPARTMENT D ON D.ID=P.DEPARTMENTID ) GS
GROUP BY DEPARTMENT  --DYNAMIC VIEW