--Q2) PLESE WRITE E = MALE , K = FEMALE IN TURKISH E=ERKEK K=KADIN
--We use the 'Case' structure where the Gender structure is.
SELECT DM.DEPARTMENT,
CASE
    WHEN P.GENDER = 'E' THEN 'MALE'
	ELSE 'FEMALE'
END AS GENDER

,COUNT(P.ID) AS PERSONCOUNT FROM PERSON P
INNER JOIN DEPARTMENT DM ON DM.ID=P.DEPARTMENTID
WHERE P.OUTDATE IS NULL --> Still working
GROUP BY  DM.DEPARTMENT, P.GENDER
ORDER BY DM.DEPARTMENT, COUNT(P.ID)