--Q3) Please bring the numbers of Women and Men who are still working on a departmental basis in our company.(Subquery)

SELECT *,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID=D.ID AND GENDER='E'  AND OUTDATE IS NULL) AS MALEPERSON,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID=D.ID AND GENDER='K' AND OUTDATE IS NULL) AS FEMALEPERSON,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID=D.ID AND OUTDATE IS NULL) AS TOTOLPERSON


FROM DEPARTMENT D 